#################################################################################
#                         OneBranch Pipelines - Official                        #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: # https://aka.ms/obpipelines/triggers
- none

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: 'rolloutType'
  displayName: 'SDP rollout type'
  type: string
  default: 'normal'
  values:
  - normal
  - emergency
  - globaloutage

- name: 'overrideManagedValidationDuration'
  displayName: 'Override standard SDP duration?'
  type: boolean
  default: false 

- name: 'managedValidationDurationInHours'
  displayName: 'Override standard SDP duration (in hours)'
  type: number
  default: 0

- name: 'icmIncidentId'
  displayName: 'IcM Incident Id'
  type: number
  default: 0

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}
  ENABLE_PRS_DELAYSIGN: 1
  ROOT: $(Build.SourcesDirectory)
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  NUGET_XMLDOC_MODE: none
  VSROOT: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\'
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      binskim:
        break: false # always break the build on binskim issues in addition to TSA upload
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
    featureFlags:
      WindowsHostVersion: 1ESWindows2022

    ev2ManagedSdpRolloutConfig:
      rolloutType: ${{parameters.rolloutType}}
      overrideManagedValidationDuration: ${{parameters.overrideManagedValidationDuration}} 
      managedValidationOverrideDurationInHours: ${{parameters.managedValidationDurationInHours}} 
      icmIncidentId: ${{parameters.icmIncidentId}}

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
        
        variables:
          ob_outputDirectory: '$(REPOROOT)\out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_sdl_binskim_break: false # https://aka.ms/obpipelines/sdl
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}: # conditionally enable symbolsPublishing for master branch only
            ob_symbolsPublishing_enabled: true # https://aka.ms/obpipelines/symbols

        steps:

          - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
            displayName: 'Setup BuildNumber'
            inputs:
              system: 'RevisionCounter'
              major: '1'
              minor: '0'
              exclude_commit: true

          - task: CSRF@1
            displayName: 'Run CSRF scan'
            inputs:
              Path: '$(Build.SourcesDirectory)'
              ToolVersion: Latest

          - task: onebranch.pipeline.signing@1 # https://aka.ms/obpipelines/signing
            displayName: 'Sign output'
            inputs:
              command: 'sign'
              signing_environment: 'azure-ado'
              files_to_sign: '**/*.exe;**/*.dll;**/*.ps1;**/*.psm1;**/*.js'
              search_root: '$(Build.SourcesDirectory)\out'

          # Alternative to Docker@2 - Use buildah for container builds
          
          - task: AzureCLI@2
            displayName: Build image in ACR (remote)
            inputs:
              azureSubscription: 'SxGCore_Eval_Prod'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $registry = "evalplatformregistrytest"
                $imageRepo = "eval-runner-app"
                $tag      = "$(Build.BuildNumber)"  # or 'latest' etc.
                $dockerfile = "$(Build.SourcesDirectory)\src\Eval-Runner\SxG.EvalPlatform.EvaluationEngine\Dockerfile"
                $context    = "$(Build.SourcesDirectory)\src\Eval-Runner\SxG.EvalPlatform.EvaluationEngine"

                # Build with explicit encoding build arguments
                az acr build `
                  --registry $registry `
                  --image "${imageRepo}:${tag}" `
                  --image "${imageRepo}:latest" `
                  --file $dockerfile `
                  --build-arg LANG=C.UTF-8 `
                  --build-arg LC_ALL=C.UTF-8 `
                  --build-arg PYTHONIOENCODING=utf-8 `
                  --platform linux/amd64 `
                  $context
                
                if ($LASTEXITCODE -ne 0) {
                  Write-Error "ACR build failed with exit code $LASTEXITCODE"
                  exit $LASTEXITCODE
                }


          # Copy Evaluation Runner EV2 files to region agnostic structure
          - task: CopyFiles@2
            displayName: 'Copy EvalRunner RegionAgnosticEv2'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\Eval-Runner\SxG.EvalPlatform.EvaluationEngine\src\EV2'
              Contents: '**/*'
              TargetFolder: '$(REPOROOT)\out\EvalRunner\EV2\RegionAgnosticEv2'

          - task: PowerShell@2
            displayName: 'Inject version in EvalRunner'
            inputs:
              targetType: 'inline'
              script: |

                # Inject version in Evaluation Runner EV2 files
                $evalRunnerParameterFiles = Get-ChildItem -Recurse -Include *.json, BuildVer.txt -File -Path $(Build.SourcesDirectory)\out\EvalRunner\EV2\RegionAgnosticEv2
                foreach ($file in $evalRunnerParameterFiles) {
                    Write-Host "Replacing contents in EvalRunner file " $file.PSPath
                    (Get-Content $file.PSPath) |
                    Foreach-Object { $_ -replace "EV2Build_Version", "$(Build.BuildNumber)" } |
                    Set-Content $file.PSPath
                }

                # Inject Docker image tag in EvalRunner templates
                $evalRunnerTemplateFiles = Get-ChildItem -Recurse -Include *.json -File -Path $(Build.SourcesDirectory)\out\EvalRunner\EV2\RegionAgnosticEv2
                foreach ($file in $evalRunnerTemplateFiles) {
                    Write-Host "Replacing Docker image tag in " $file.PSPath
                    (Get-Content $file.PSPath) |
                    Foreach-Object { $_ -replace "DOCKER_IMAGE_TAG", "$(Build.BuildNumber)" } |
                    Set-Content $file.PSPath
                }

    - stage: 'Prod_EvalRunner_Release'
      trigger: manual
      displayName: 'Region Agnostic EvalRunner Deployment'
      variables:
        ob_release_environment: Production
        ob_release_stagetype: deployment
        ArtifactToDeploy: drop_build_main
        CvrpManifestRelativePath: \build.manifest
      jobs:
      - job: DeployEvalRunner
        displayName: 'Deploy EvalRunner Container App'
        pool:
          type: release # read more about custom job types at https://aka.ms/obpipelines/yaml/jobs
        steps:

          - download: current
            artifact: drop_build_main

          - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
            displayName: 'Setup BuildNumber'
            inputs:
              system: 'RevisionCounter'
              major: '1'
              minor: '0'
              exclude_commit: true

          - task: vsrm-ev2.ev2-rollout.ev2-rollout-task.Ev2RARollout@2
            displayName: 'Ev2 EvalRunner Resource Rollout'
            inputs:
              UseServerMonitorTask: false
              EndpointProviderType: ApprovalService
              ApprovalServiceEnvironment: Production
              artifactsVersionOverride: $(Build.BuildNumber)
              TaskAction: RegisterAndRollout
              forceRegistration: True
              SkipRegistrationIfExists: true
              ServiceRootLocation: 'LinkedArtifact'
              ServiceRootPath: $(Pipeline.Workspace)/drop_build_main/EvalRunner/EV2
              RolloutSpecPath: $(Pipeline.Workspace)/drop_build_main/EvalRunner/EV2/RegionAgnosticEv2/Prod.RolloutSpec.json
              StageMapName: 'Microsoft.Azure.SDP.Standard'
              Select: regions(*)