//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxG.EvalPlatform.Plugins.Models
{


    [System.Runtime.Serialization.DataContractAttribute()]
    public enum cr890_evalrun_cr890_status
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr890_evalrun")]
    public partial class EvalRun : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Available fields, a the time of codegen, for the cr890_evalrun entity
        /// </summary>
        public partial class Fields
        {
            public const string cr890_AgentId = "cr890_agentid";
            public const string cr890_AgentSchemaName = "cr890_agentschemaname";
            public const string cr890_Dataset = "cr890_dataset";
            public const string cr890_DatasetId = "cr890_datasetid";
            public const string cr890_EnvironmentId = "cr890_environmentid";
            public const string cr890_EvalRunId = "cr890_evalrunid";
            public const string Id = "cr890_evalrunid";
            public const string cr890_Id = "cr890_id";
            public const string cr890_Status = "cr890_status";
            public const string CreatedBy = "createdby";
            public const string CreatedOn = "createdon";
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            public const string ImportSequenceNumber = "importsequencenumber";
            public const string ModifiedBy = "modifiedby";
            public const string ModifiedOn = "modifiedon";
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            public const string OverriddenCreatedOn = "overriddencreatedon";
            public const string OwnerId = "ownerid";
            public const string OwningBusinessUnit = "owningbusinessunit";
            public const string OwningTeam = "owningteam";
            public const string OwningUser = "owninguser";
            public const string PartitionId = "partitionid";
            public const string TTLInSeconds = "ttlinseconds";
            public const string VersionNumber = "versionnumber";
        }

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public EvalRun() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "cr890_evalrun";

        public const string EntityLogicalCollectionName = "cr890_evalruns";

        public const string EntitySetName = "cr890_evalruns";

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_agentid")]
        public string cr890_AgentId
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_agentid");
            }
            set
            {
                this.OnPropertyChanging("cr890_AgentId");
                this.SetAttributeValue("cr890_agentid", value);
                this.OnPropertyChanged("cr890_AgentId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_agentschemaname")]
        public string cr890_AgentSchemaName
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_agentschemaname");
            }
            set
            {
                this.OnPropertyChanging("cr890_AgentSchemaName");
                this.SetAttributeValue("cr890_agentschemaname", value);
                this.OnPropertyChanged("cr890_AgentSchemaName");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_dataset")]
        public string cr890_Dataset
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_dataset");
            }
            set
            {
                this.OnPropertyChanging("cr890_Dataset");
                this.SetAttributeValue("cr890_dataset", value);
                this.OnPropertyChanged("cr890_Dataset");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_datasetid")]
        public string cr890_DatasetId
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_datasetid");
            }
            set
            {
                this.OnPropertyChanging("cr890_DatasetId");
                this.SetAttributeValue("cr890_datasetid", value);
                this.OnPropertyChanged("cr890_DatasetId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_environmentid")]
        public string cr890_EnvironmentId
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_environmentid");
            }
            set
            {
                this.OnPropertyChanging("cr890_EnvironmentId");
                this.SetAttributeValue("cr890_environmentid", value);
                this.OnPropertyChanged("cr890_EnvironmentId");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_evalrunid")]
        public System.Nullable<System.Guid> cr890_EvalRunId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("cr890_evalrunid");
            }
            set
            {
                this.OnPropertyChanging("cr890_EvalRunId");
                this.SetAttributeValue("cr890_evalrunid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("cr890_EvalRunId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_evalrunid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.cr890_EvalRunId = value;
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_id")]
        public string cr890_Id
        {
            get
            {
                return this.GetAttributeValue<string>("cr890_id");
            }
            set
            {
                this.OnPropertyChanging("cr890_Id");
                this.SetAttributeValue("cr890_id", value);
                this.OnPropertyChanged("cr890_Id");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr890_status")]
        public virtual cr890_evalrun_cr890_status? cr890_Status
        {
            get
            {
                return ((cr890_evalrun_cr890_status?)(EntityOptionSetEnum.GetEnum(this, "cr890_status")));
            }
            set
            {
                this.OnPropertyChanging("cr890_Status");
                this.SetAttributeValue("cr890_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : new Microsoft.Xrm.Sdk.OptionSetValue((int) cr890_evalrun_cr890_status.New));
                this.OnPropertyChanged("cr890_Status");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Logical partition id. A logical partition consists of a set of records with same partition id.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("partitionid")]
        public string PartitionId
        {
            get
            {
                return this.GetAttributeValue<string>("partitionid");
            }
            set
            {
                this.OnPropertyChanging("PartitionId");
                this.SetAttributeValue("partitionid", value);
                this.OnPropertyChanged("PartitionId");
            }
        }

        /// <summary>
        /// Time to live in seconds.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ttlinseconds")]
        public System.Nullable<int> TTLInSeconds
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("ttlinseconds");
            }
            set
            {
                this.OnPropertyChanging("TTLInSeconds");
                this.SetAttributeValue("ttlinseconds", value);
                this.OnPropertyChanged("TTLInSeconds");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }
    }
}
